// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CounterButtons: typeof import('./src/components/CounterButtons.vue')['default']
    Pokedex: typeof import('./src/components/Pokedex.vue')['default']
  }
}

export { }
